# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6eaf44277a2f62bca58c1cb59d744a35aef62031be049a4feebb7d4cc0637bd12002ac5103a5611379632b7430a52450b0397264cab79cd137e58b63bce521c3

test:
  secret_key_base: d47ec5b89baa42976b387a71b1fdb491c6af52e8e264c30fe75030846998e4d8dae25e9388171568c33b26e1e9499d09c6a8c838370e38fa5ef2cfa85a5a849c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["EPBOOK_SECRET_KEY_BASE"] %>
